<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PS-WIN-LP-91" ignored="0" name="Lead Test" tests="6" failures="1" timestamp="10 Jun 2019 09:12:17 GMT" time="287.176" errors="0">
  <testcase name="createLeadTest" time="79.269" classname="com.qtpselenium.zoho.project.testcases.LeadTest"/>
  <testcase name="createLeadTest" time="49.865" classname="com.qtpselenium.zoho.project.testcases.LeadTest"/>
  <testcase name="createLeadTest" time="0.003" classname="com.qtpselenium.zoho.project.testcases.LeadTest">
    <skipped/>
  </testcase> <!-- createLeadTest -->
  <testcase name="createLeadTest" time="0.003" classname="com.qtpselenium.zoho.project.testcases.LeadTest">
    <skipped/>
  </testcase> <!-- createLeadTest -->
  <testcase name="convertLeadTest" time="74.671" classname="com.qtpselenium.zoho.project.testcases.LeadTest"/>
  <testcase name="deleteLeadAccountTest" time="64.07" classname="com.qtpselenium.zoho.project.testcases.LeadTest">
    <failure type="java.lang.AssertionError" message="Could not delete the lead">
      <![CDATA[java.lang.AssertionError: Could not delete the lead
at com.qtpselenium.zoho.project.base.BaseTest.reportFailure(BaseTest.java:219)
at com.qtpselenium.zoho.project.testcases.LeadTest.deleteLeadAccountTest(LeadTest.java:117)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- deleteLeadAccountTest -->
</testsuite> <!-- Lead Test -->
